import Head from "next/head";
import Button from "@mui/material/Button";
import { Box } from "@mui/material";

const Home = () => {
  return (
    <>
      <Head>
        <title>Food Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main>
        <Button
          disableRipple
          variant="text"
          sx={{
            ":hover": {
              bgcolor: "transparent",
              color: "green ",
            },
          }}
        >
          Нүүр
        </Button>
      </main>
    </>
  );
};
export default Home;
